services:
  db:
    image: postgres:16
    container_name: usuarios_db
    environment:
      POSTGRES_DB: usuariosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usuariosdb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
